version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Taralej87
      POSTGRES_USER: postgres-user
      POSTGRES_DB: postgresDB
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    user: "${UID}:${GID}"  # to avoid permission issues
    environment:
      PGADMIN_DEFAULT_EMAIL: anyone@softuni.bg
      PGADMIN_DEFAULT_PASSWORD: Taralej87
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
    ports:
      - "5433:80"
    depends_on:
      - postgres
docker-compose up -d
